version: '2'
services:
  celery-worker:
    image: xxxxxxxxxxxxxxxxxxxxx/ly_ops/check_ssl:${VERSION}
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_HOST: xxxxxxxxxxxxxxxxxxxx
      DATABASE_NAME: check_ssl
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: '3306'
      DATABASE_USER: check_ssl
      LOG_PATH: '/dev/null'
      MSG_NOTIFY_ID: '19'
      MSG_TOKEN: ${MSG_TOKEN}
    stdin_open: true
    tty: true
    links:
    - redis:redis
    command:
    - celery
    - worker
    - -l
    - info
    - -A
    - check_ssl
    labels:
      io.rancher.container.pull_image: always
  checkssl-backend:
    image: xxxxxxxxxxxxxx/ly_ops/check_ssl:${VERSION}
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_HOST: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      DATABASE_NAME: check_ssl
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: '3306'
      DATABASE_USER: check_ssl
      #LOG_PATH: '/dev/stdout'
      MSG_NOTIFY_ID: '19'
      MSG_TOKEN: ${MSG_TOKEN}
    stdin_open: true
    entrypoint:
    - python
    - manage.py
    - runserver
    - 0.0.0.0:8000
    tty: true
    links:
    - redis:redis
    labels:
      io.rancher.container.pull_image: always
  celery-beat:
    image: xxxxxxxxxxxxxxxx/ly_ops/check_ssl:${VERSION}
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_HOST: xxxxxxxxxxxx
      DATABASE_NAME: check_ssl
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: '3306'
      DATABASE_USER: check_ssl
      LOG_PATH: '/dev/null'
      MSG_NOTIFY_ID: '19'
      MSG_TOKEN: ${MSG_TOKEN}
    stdin_open: true
    tty: true
    links:
    - redis:redis
    command:
    - celery
    - beat
    - -A
    - check_ssl
    - -l
    - info
    - --scheduler
    - django_celery_beat.schedulers:DatabaseScheduler
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
