# see https://docs.gitlab.com/ce/ci/docker/using_docker_build.html to learn more :-)
image: docker:latest
stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  REGISTRY_USER: $REGISTRY_USER
  REGISTRY_PASSWORD: $REGISTRY_PASSWORD
  NAMESPACE: ly_ops

build_image:
  #variables:
  #  CI_DEBUG_TRACE: "true"  # 除非调试，不要启用这个选项
  stage: build
  before_script:
    - echo "docker registry user：$REGISTRY_USER"
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
  script:
    - docker build -t $REGISTRY/$NAMESPACE/check_ssl:${CI_COMMIT_TAG##v} -f Dockerfile .
    - docker push $REGISTRY/$NAMESPACE/check_ssl:${CI_COMMIT_TAG##v}
  tags:
    - rancher
    - dev
  only:
    - tags
    - triggers
    - schedules
  except:
    - master
    - dev

deploy_staging:
  image:
    name: i.harbor.dragonest.net/public/rancher-cli:v0.6.5
    entrypoint: [""]
  stage: deploy
  before_script:
    - export RANCHER_ACCESS_KEY=${RANCHER_ACCESS_KEY}
    - export RANCHER_SECRET_KEY="${RANCHER_SECRET_KEY}"
    - export RANCHER_URL="http://rancher.ops.dragonest.com/v2-beta/schemas"
    - export RANCHER_ENVIRONMENT="1a24084"
    - export SSL_VERIFY="false"
    - export VERSION=${CI_COMMIT_TAG##v}
    - /entrypoint.sh
  script:
    - cd tools/rancher-deploy && rancher up -s check_ssl -u -d -c
  tags:
    - rancher
    - dev
  only:
    - tags
    - triggers
    - schedules
  except:
    - master
    - dev
  when: manual