# see https://docs.gitlab.com/ce/ci/docker/using_docker_build.html to learn more :-)
image: docker:latest
stages:
  - build
  - deploy-qa

services:
  - docker:dind

variables:
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  REGISTRY_USER: $REGISTRY_USER
  REGISTRY_PASSWORD: $REGISTRY_PASSWORD
  NAMESPACE: ly_ops

build_image:
  #variables:
  #  CI_DEBUG_TRACE: "true"  # 除非调试，不要启用这个选项
  stage: build
  before_script:
    - echo "docker registry user：$REGISTRY_USER"
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
  script:
    - docker build -t $REGISTRY/$NAMESPACE/check_ssl:${CI_COMMIT_TAG##v} -f Dockerfile .
    - docker push $REGISTRY/$NAMESPACE/check_ssl:${CI_COMMIT_TAG##v}
  tags:
    - rancher
    - dev
  only:
    - tags
    - triggers
    - schedules
  except:
    - master
    - dev

deploy-qa-checkssl-backend:
  image: i.harbor.dragonest.net/public/kubectl:v1.11.0.gitlab-cicd
  stage: deploy-qa
  variables:
    K8S_API_SERVER: ${K8S_API_SERVER}
    TOKEN: ${KUBECTL_TOKEN}
    NAMESPACE: ops-qa
    DEPLOYMENT_NAME: checkssl-dep
    CONTAINER_NAME: checkssl-backend
    IMAGE: registry.cn-shanghai.aliyuncs.com/ly_ops/check_ssl
    VERSION: ${CI_COMMIT_TAG}
  script:
    - /gitlab-cicd.sh
  tags:
    - rancher
    - dev
  only:
    - tags
  when: manual

deploy-qa-celery-worker:
  image: i.harbor.dragonest.net/public/kubectl:v1.11.0.gitlab-cicd
  stage: deploy-qa
  variables:
    K8S_API_SERVER: ${K8S_API_SERVER}
    TOKEN: ${KUBECTL_TOKEN}
    NAMESPACE: ops-qa
    DEPLOYMENT_NAME: checkssl-dep
    CONTAINER_NAME: celery-worker
    IMAGE: registry.cn-shanghai.aliyuncs.com/ly_ops/check_ssl
    VERSION: ${CI_COMMIT_TAG}
  script:
    - /gitlab-cicd.sh
  tags:
    - rancher
    - dev
  only:
    - tags
  when: manual

deploy-qa-celery-beta:
  image: i.harbor.dragonest.net/public/kubectl:v1.11.0.gitlab-cicd
  stage: deploy-qa
  variables:
    K8S_API_SERVER: ${K8S_API_SERVER}
    TOKEN: ${KUBECTL_TOKEN}
    NAMESPACE: ops-qa
    DEPLOYMENT_NAME: checkssl-dep
    CONTAINER_NAME: celery-beta
    IMAGE: registry.cn-shanghai.aliyuncs.com/ly_ops/check_ssl
    VERSION: ${CI_COMMIT_TAG}
  script:
    - /gitlab-cicd.sh
  tags:
    - rancher
    - dev
  only:
    - tags
  when: manual