version: '2'
services:
  celery-worker:
    image: registry.cn-shanghai.aliyuncs.com/ly_ops/check_ssl:0.0.2
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_HOST: rm-uf6n05p6m8rf2nq7l.mysql.rds.aliyuncs.com
      DATABASE_NAME: check_ssl
      DATABASE_PASSWORD: 9Jckimq5Bf
      DATABASE_PORT: '3306'
      DATABASE_USER: check_ssl
      LOG_PATH: '/dev/stdout'
      MSG_NOTIFY_ID: '19'
      MSG_TOKEN: 'c25fa3f66b02c8b83cff9090125df91db288cecb'
    stdin_open: true
    tty: true
    links:
    - redis:redis
    command:
    - celery
    - worker
    - -l
    - info
    - -A
    - check_ssl
    labels:
      io.rancher.container.pull_image: always
  checkssl-backend:
    image: registry.cn-shanghai.aliyuncs.com/ly_ops/check_ssl:0.0.2
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_HOST: rm-uf6n05p6m8rf2nq7l.mysql.rds.aliyuncs.com
      DATABASE_NAME: check_ssl
      DATABASE_PASSWORD: 9Jckimq5Bf
      DATABASE_PORT: '3306'
      DATABASE_USER: check_ssl
      LOG_PATH: '/dev/stdout'
      MSG_NOTIFY_ID: '19'
      MSG_TOKEN: 'c25fa3f66b02c8b83cff9090125df91db288cecb'
    stdin_open: true
    entrypoint:
    - python
    - manage.py
    - runserver
    - 0.0.0.0:8000
    tty: true
    links:
    - redis:redis
    ports:
    - 8000:8000/tcp
    labels:
      io.rancher.container.pull_image: always
  celery-beat:
    image: registry.cn-shanghai.aliyuncs.com/ly_ops/check_ssl:0.0.2
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_HOST: rm-uf6n05p6m8rf2nq7l.mysql.rds.aliyuncs.com
      DATABASE_NAME: check_ssl
      DATABASE_PASSWORD: 9Jckimq5Bf
      DATABASE_PORT: '3306'
      DATABASE_USER: check_ssl
      LOG_PATH: '/dev/stdout'
      MSG_NOTIFY_ID: '19'
      MSG_TOKEN: 'c25fa3f66b02c8b83cff9090125df91db288cecb'
    stdin_open: true
    tty: true
    links:
    - redis:redis
    command:
    - celery
    - beat
    - -A
    - config
    - -l
    - info
    - --scheduler
    - django_celery_beat.schedulers:DatabaseScheduler
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
