# Generated by Django 2.1.5 on 2019-01-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='业务域名', max_length=50, verbose_name='域名')),
                ('domain_port', models.IntegerField(help_text='端口', max_length=10, verbose_name='端口')),
                ('domain_comment', models.TextField(help_text='备注', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
            },
        ),
        migrations.CreateModel(
            name='domain_https',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_https_name', models.CharField(help_text='业务域名', max_length=50, verbose_name='域名')),
                ('domain_https_ca', models.CharField(help_text='域名CA', max_length=50, verbose_name='CA中心')),
                ('domain_https_starttime', models.CharField(help_text='域名证书申请时间', max_length=50, verbose_name='申请时间')),
                ('domain_https_endtime', models.CharField(help_text='域名证书到期时间', max_length=50, verbose_name='到期时间')),
                ('domain_https_chrome', models.BooleanField(default=True, help_text='域名证书是否被Chrome信任', max_length=10, verbose_name='证书是否被Chrome信任')),
            ],
            options={
                'verbose_name': '证书信息',
                'verbose_name_plural': '证书信息',
            },
        ),
    ]
