# Generated by Django 2.1.5 on 2019-01-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_https', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_port',
            field=models.IntegerField(help_text='端口', verbose_name='端口'),
        ),
    ]
