# Generated by Django 2.1.5 on 2019-01-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_https', '0002_auto_20190125_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_comment',
            field=models.TextField(blank=True, help_text='备注', max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_port',
            field=models.IntegerField(default=443, help_text='端口', verbose_name='端口'),
        ),
    ]
