# Generated by Django 2.1.5 on 2019-01-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_https', '0003_auto_20190125_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_overseas',
            field=models.BooleanField(default=False, help_text='是否有海外https', verbose_name='是否有海外HTTPS'),
        ),
    ]
